server.name: "centos7"
server.host: "0.0.0.0"
logging.verbose: true
#elasticsearch.url: "http://localhost:9200"
elasticsearch.username: "kibana"
elasticsearch.password: "changeme"

xpack.security.encryptionKey: "MjAxOC0wOS0yMFQxODo0ODowNlogMjAxODA5MjBfMTg0OCAxNTM3NDY5Mjg2NzQx"
xpack.reporting.encryptionKey: "MjAxOC0wOS0yMFQxODo0ODowNlogMjAxODA5MjBfMTg0OCAxNTM3NDY5Mjg2NzQx"
