server.name: "centos7"
server.host: "0.0.0.0"
logging.verbose: true
elasticsearch.hosts: "https://paninix:9200"
elasticsearch.ssl.certificateAuthorities: "config/cert-bundle/ca/ca.crt"

elasticsearch.username: "kibana"
elasticsearch.password: "changeme"

server.ssl.certificate: "config/cert-bundle/localhost/localhost.crt"
server.ssl.key: "config/cert-bundle/localhost/localhost.key"
server.ssl.enabled: true

xpack.reporting.encryptionKey: "722b74f0-b882-11e8-a6d9-e546fe2bba5f"
xpack.security.encryptionKey: "722b74f0-b882-11e8-a6d9-e546fe2bba5f"
xpack.reporting.capture.maxAttempts: 3

# test diagnostic
xpack.reporting.capture.browser.chromium.disableSandbox: false

