server.host: 0.0.0.0

elasticsearch:
  username: "kibana_system"
  password: "changeme"
  hosts: ['https://elasticsearch:9200']
  ssl.certificateAuthorities: ['config/cert-bundle/ca/ca.crt']

logging:
  appenders:
    file:
      type: file
      fileName: /home/vagrant/log/kibana.log
      layout:
        type: json
  root:
    appenders: [default, file]
  loggers:
    - name: plugins.reporting
      appenders: [file]
      level: debug

xpack.reporting:
  encryptionKey: fixme
  roles.enabled: false
  capture.timeouts:
    renderComplete: 1m
    waitForElements: 1m
